name: "Download MinGW-w64"
description: "Downloads a specific MinGW-w64 build by ray_linn for myself (Windows only)"

inputs:
  path:
    description: "Where to put the compiler in (must be a path to a directory that exists; compiler will be in a subdirectory)"
    required: true
    default: "C:"
  download-url:
    description: "URL to the compiler download archive"
    required: true
    default: "https://master.dl.sourceforge.net/mingw-w64/Multilib Toolchains(Targetting Win32 and Win64)/ray_linn/gcc-10.x-with-ada/mingw64-10.2.0-crt-8.0.0-with-ada.7z"
outputs:
  path:
    description: "Path to compiler"
    value: ${{ inputs.path }}\mingw64
runs:
  using: "composite"
  steps:
  - shell: cmd
    working-directory: ${{ runner.temp }}
    run: |
      echo Downloading gcc
      curl -L -s -o 1.7z "${{ inputs.download-url }}"
      echo Extracting gcc
      7z x 1.7z -o"${{ inputs.path }}" -y -aoa -bb0 -bso0
      del 1.7z
      echo.
  - shell: cmd
    working-directory: ${{ inputs.path }}\mingw64
    run: |
      echo Preparing MinGW-w64
      cmd /c setup.bat > nul
      echo ${{ inputs.path }}\mingw64\bin>> %GITHUB_PATH%
  - shell: cmd
    run: |
      refreshenv > nul
  - shell: cmd
    run: |
      echo.
      echo Success! Installed in
      echo ${{ inputs.path }}\mingw64
      echo and added to PATH
      echo.
      gcc -v
      g++ -v
