name: "Download MinGW-w64"
description: "Downloads a specific MinGW-w64 build by ray_linn for myself (Windows only)"

inputs:
  path:
    description: "Where to put the directory in (must be a path to a directory that exists)"
    required: true
    default: "C:"
  download-url:
    description: "File URL"
    required: true
    default: "https://master.dl.sourceforge.net/mingw-w64/Multilib Toolchains(Targetting Win32 and Win64)/ray_linn/gcc-10.x-with-ada/mingw64-10.2.0-crt-8.0.0-with-ada.7z"
outputs:
  path:
    description: "Path of unpacked files"
    value: ${{ inputs.path }}\mingw64
runs:
  using: "composite"
  steps:
  #- if: "runner.os != 'Windows'"
  #  shell: sh
  #  run: |
  #    echo This action is for Windows only.
  #    exit 1
  - shell: cmd
    working-directory: ${{ runner.temp }}
    run: |
      echo Downloading gcc
      curl -L -s -o 1.7z "${{ inputs.download-url }}"
      echo Extracting gcc
      7z x 1.7z -o"${{ inputs.path }}" -y -aoa -bb0 -bso0
      del 1.7z
      echo.
  - shell: cmd
    #continue-on-error: true
    run: |
      echo Uninstalling mingw from choco if exists
      forfiles /p C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64 /s /m *.exe /C "cmd /c del /q C:\ProgramData\chocolatey\bin\@file > nul"
      del /s /q C:\ProgramData\chocolatey\lib\mingw\tools\install\*.* > nul
      rd /s /q C:\ProgramData\chocolatey\lib\mingw\tools\install > nul
  - shell: cmd
    working-directory: ${{ inputs.path }}\mingw64
    run: |
      echo Preparing MinGW-w64
      cmd /c setup.bat
      set GITHUB_PATH="${{ inputs.path }}\mingw64\bin;%GITHUB_PATH%"
  - shell: cmd
    working-directory: ${{ inputs.path }}\mingw64\bin
    run: |
      refreshenv
      gcc -v 1>nul 2>nul
      echo int main() { return 0; } > ${{ runner.temp }}\test.c
      gcc -o ${{ runner.temp }}\test.exe ${{ runner.temp }}\test.c
      ${{ runner.temp }}\test.exe && echo Test program compiles and runs
  - shell: cmd
    run: |
      echo.
      echo Success! Installed in
      echo ${{ inputs.path }}\mingw64
